spring:
  application:
    name: gymbuddy-back
  datasource:
    url: jdbc:mysql://localhost:3306/gymbuddy
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: a01051153088@gmail.com
    password: ltts brby fwoq npyr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
  data:
    redis:
      host: localhost
      port: 6379